services:
  db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  test-db:
    image: postgres
    ports:
      - 5434:5435
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  app:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      ENVIRONMENT: development
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
    command: 'npm run start:dev'

  tests-runner:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - test-db
    environment:
      ENVIRONMENT: test
      DATABASE_HOST: test-db
      DATABASE_PORT: 5435
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
    command: npm run test
